# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(max_length=8)),
                ('cor_veiculo', models.CharField(max_length=10)),
                ('modelo_veiculo', models.CharField(max_length=50)),
                ('marca_veiculo', models.CharField(max_length=50)),
                ('ano_veiculo', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
            },
        ),
    ]
