# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('cd_motorista', models.AutoField(primary_key=True, serialize=False)),
                ('nome_motorista', models.CharField(max_length=50)),
                ('cpf_motorista', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='id',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa_veiculo',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='motorista',
            name='placa_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Veiculo'),
        ),
    ]
