# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171105_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('cd_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('ds_ocorrencia', models.CharField(max_length=100)),
                ('local_ocorrencia', models.CharField(max_length=100)),
                ('data_ocorrencia', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('cd_viagem', models.AutoField(primary_key=True, serialize=False)),
                ('origem_viagem', models.CharField(max_length=100)),
                ('destino_viagem', models.CharField(max_length=100)),
                ('data_inicio_viagem', models.DateTimeField(blank=True, null=True)),
                ('data_fim_viagem', models.DateTimeField(blank=True, null=True)),
                ('status_viagem', models.BooleanField()),
                ('cd_ocorrencia', models.ManyToManyField(to='app.Ocorrencia')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
            },
        ),
    ]
