# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ocorrencia_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='cd_ocorrencia',
            field=models.ManyToManyField(null=True, to='app.Ocorrencia'),
        ),
    ]
