# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171105_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViagemOcorrencia',
            fields=[
                ('cd_viagem_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('cd_ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ocorrencia')),
                ('cd_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Viagem')),
            ],
            options={
                'verbose_name': 'Viagem Ocorrencia',
                'verbose_name_plural': 'Viagem e Ocorrencias',
            },
        ),
    ]
