# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_viagemocorrencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagemocorrencia',
            name='cd_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='viagemocorrencia',
            name='cd_viagem',
        ),
        migrations.DeleteModel(
            name='ViagemOcorrencia',
        ),
    ]
