# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171106_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='status_ocorrencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='status_viagem',
            field=models.CharField(choices=[(b'finalizada', b'Finalizada'), (b'em_andamento', b'Em Andamento'), (b'nao_iniciada', b'Nao Iniciada')], default=b'nao_iniciada', max_length=64),
        ),
    ]
