# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171106_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagemocorrencia',
            name='cd_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='viagemocorrencia',
            name='cd_viagem',
        ),
        migrations.AddField(
            model_name='viagem',
            name='cd_ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ocorrencia'),
        ),
        migrations.DeleteModel(
            name='ViagemOcorrencia',
        ),
    ]
