# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171107_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='cd_ocorrencia',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='cd_viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Viagem'),
        ),
    ]
