# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20171110_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano_veiculo',
            field=models.CharField(choices=[(b'2007', b'2007'), (b'2008', b'2008'), (b'2009', b'2009'), (b'2010', b'2010'), (b'2011', b'2011'), (b'2012', b'2012'), (b'2013', b'2013'), (b'2014', b'2014'), (b'2015', b'2015'), (b'2016', b'2016'), (b'2017', b'2017'), (b'2018', b'2018')], max_length=4),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca_veiculo',
            field=models.CharField(choices=[(b'Mercedes-Benz', b'Mercedes-Benz'), (b'MAN (VW)', b'MAN (VW)'), (b'Ford Caminhoes', b'Ford Caminhoes'), (b'Volvo', b'Volvo')], default=b'nao_iniciada', max_length=64),
        ),
    ]
