# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171112_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='origem_viagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
