# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171112_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='cd_motorista_viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Motorista'),
        ),
    ]
