# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20171112_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='status_viagem',
            field=models.CharField(choices=[(b'nao_iniciada', b'Nao Iniciada'), (b'finalizada', b'Finalizada'), (b'em_andamento', b'Em Andamento'), (b'cancelada', b'Cancelada')], default=b'nao_iniciada', max_length=64),
        ),
    ]
