# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20171113_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadasVeiculo',
            fields=[
                ('cd_coordenada', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('porta_aberta', models.BooleanField(default=False)),
                ('cd_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Viagem')),
            ],
            options={
                'verbose_name': 'Coordenada',
                'verbose_name_plural': 'Coordenadas',
            },
        ),
    ]
